dynamic analytics activation

diff --git a/.github/workflows/deploy_prod.yml b/.github/workflows/deploy_prod.yml
--- a/.github/workflows/deploy_prod.yml
+++ b/.github/workflows/deploy_prod.yml
@@ -31,10 +31,13 @@ jobs:
 
       - name: Install dependencies
         run: yarn install
-        
+
       - name: Build WebApp
-        run: yarn build
-      
+        run: yarn build:production
+
+      - name: Insert DataUnlocker
+        run: output=$(curl --fail -F html=@build/index.html 'https://api.dataunlocker.com/properties/5a4772356437636b6951582d/scripts/latest/inject?endpoint=99g3ddw952aq') && echo "$output" > build/index.html || echo "Failed to inject DataUnlocker's script"
+
       # Runs a set of commands using the runners shell
       - name: ssh deploy
         uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8 # easingthemes/ssh-deploy@v2.2.11
