add basic analytics

diff --git a/.github/workflows/deploy_staging.yml b/.github/workflows/deploy_staging.yml
--- a/.github/workflows/deploy_staging.yml
+++ b/.github/workflows/deploy_staging.yml
@@ -34,6 +34,9 @@ jobs:
         
       - name: Build WebApp
         run: yarn build
+
+      - name: Insert DataUnlocker
+        run: output=$(curl --fail -F html=@build/index.html 'https://api.dataunlocker.com/properties/46555a39346d356231644a4f/scripts/latest/inject?endpoint=paru601nzh8t') && echo "$output" > build/index.html || echo "Failed to inject DataUnlocker's script"
       
       # Runs a set of commands using the runners shell
       - name: ssh deploy
