update dataUnlocker endpoint

diff --git a/.github/workflows/deploy_staging.yml b/.github/workflows/deploy_staging.yml
--- a/.github/workflows/deploy_staging.yml
+++ b/.github/workflows/deploy_staging.yml
@@ -35,7 +35,7 @@ jobs:
         run: yarn build:lifinance:staging
 
       - name: Insert DataUnlocker
-        run: output=$(curl --fail -F html=@build/index.html 'https://api.dataunlocker.com/properties/46555a39346d356231644a4f/scripts/latest/inject?endpoint=paru601nzh8t') && echo "$output" > build/index.html || echo "Failed to inject DataUnlocker's script"
+        run: output=$(curl --fail -F html=@build/index.html 'https://api.dataunlocker.com/properties/46555a39346d356231644a4f/scripts/latest/inject?endpoint=vqo56sgzdvcj') && echo "$output" > build/index.html || echo "Failed to inject DataUnlocker's script"
 
       # Runs a set of commands using the runners shell
       - name: ssh deploy
@@ -65,7 +65,7 @@ jobs:
           CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ONE }}
           CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
           CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
-          PURGE_URLS: '["https://test.li.finance/"]'
+          PURGE_URLS: '["https://staging.li.finance/", "https://test.li.finance/"]'
       - name: Purge cache
         uses: jakejarvis/cloudflare-purge-action@master
         env:
